### ISSUE TITLE
_init_.py has only one line!

### ISSUE THREAD

**Issue by cjx-fighting** [maozaizhou/py_obca#1]
Your file “_init_.py” has only one line, whether there is error?

**Comment by cjx-fighting** [comment]
start : 7.5 4.0 0.0
goal  : 7.6 1.25 0.0
searching...
goal reach!
iteration:  211238
{'x': 7.520455451367432, 'y': 1.2941479864736902, 'heading': 0.0, 'v': 0, 'a': 0, 'steer': 0, 'index': -1, 'x_index': 50, 'y_index': 8, 'heading_index': 35, 'visited': True, 'direction_index': 3, 'parent': [49, 8, 36], 'cost_to_hear': 6.090000000000002, 'cost_to_goal': 0.09097461144099482, 'move_angle': 0.08975979010256552}
Traceback (most recent call last):
  File "C:\Users\32411\OneDrive\Desktop\py_obca-main\example\example_parallel.py", line 94, in <module>
    parallel_parking()
  File "C:\Users\32411\OneDrive\Desktop\py_obca-main\example\example_parallel.py", line 48, in parallel_parking
    optimizer.generate_constrain()
  File "C:\Users\32411\OneDrive\Desktop\py_obca-main\pyobca\optimizer.py", line 147, in generate_constrain
    A, b = compute_polytope_halfspaces(obstacle)
  File "D:\Download\ANACONDA\envs\pyobca\lib\site-packages\pypoman\duality.py", line 85, in compute_polytope_halfspaces
    mat = cdd.Matrix(tV, number_type="float")
TypeError: __init__() takes exactly 0 positional arguments (1 given)
